This is makeindex, version 2.15 [TeX Live 2019] (kpathsea + Thai support).
Scanning style file /Users/sebastianschack/Documents/MA_Vorlage/mt_ssch_MWINF18/.texpadtmp/MA.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file /Users/sebastianschack/Documents/MA_Vorlage/mt_ssch_MWINF18/.texpadtmp/MA.acn....done (93 entries accepted, 0 rejected).
Sorting entries....done (636 comparisons).
Generating output file /Users/sebastianschack/Documents/MA_Vorlage/mt_ssch_MWINF18/.texpadtmp/MA.acr....done (65 lines written, 0 warnings).
Output written in /Users/sebastianschack/Documents/MA_Vorlage/mt_ssch_MWINF18/.texpadtmp/MA.acr.
Transcript written in /Users/sebastianschack/Documents/MA_Vorlage/mt_ssch_MWINF18/.texpadtmp/MA.alg.
